### ISSUE TITLE
Bug in division

### ISSUE THREAD

**Issue by peterolson** [silentmatt/javascript-biginteger#18]
The division

    BigInteger.parse("12345678901234567890123456789012345678901234567890123456789012345678901234567890")
      .divide(BigInteger.parse("1234567890"))
      .toString()

should return

    "10000000001000000000100000000010000000001000000000100000000010000000001"

but instead returns 

    "10000000000000000000000000000000000000000000000000000000000000000000000"

**Comment by Yaffle** [comment]
```
		part._d.unshift(b_digits[--b_index]);
+              part._s = 1;
```
?
