### ISSUE TITLE
Tagged Version

### ISSUE THREAD

**Issue by ipbc-dev** [silentmatt/javascript-biginteger#24]
We're using your code in an Firefox Extension and their guidelines ask to link to specific tagged version of third party libraries, if you could add a tag for the latest version we'd appreciate it very much, thank you.

**Comment by ashnur** [comment]
Without saying that this library isn't great, have you tried to use https://github.com/GoogleChromeLabs/jsbi 
It has the same API as the - BigInts coming in Firefox too will have

**Comment by ipbc-dev** [comment]
Yes, unfortunately another library we use is currently dependent on a slight difference between this and the standard in that it's trying to use BigInt as a constructor. We haven't yet had time to change that to use the newer standard compliant/native implementation.

**Comment by silentmatt** [comment]
Added a [v0.9.1 tag](https://github.com/silentmatt/javascript-biginteger/tree/v0.9.1).
